const actionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  SET_ANIMATION: 'SET_ANIMATION',
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  CLEAR_ITEM:"CLEAR_ITEM",
  ALL_CART_CLEAR:"ALL_CART_CLEAR",
};

export default actionTypes;