const actionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  SET_ANIMATION: 'SET_ANIMATION',
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  CLEAR_ITEM: 'CLEAR_ITEM',
  ALL_CART_CLEAR: 'ALL_CART_CLEAR',
  SET_COLLECTIONS: 'SET_COLLECTIONS',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',

  FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
  FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_FAILURE',

  GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
  EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',

  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',

  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
};

export default actionTypes;